package com.minivision.machinefacerecognition.activity.dailydb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.minivision.machinefacerecognition.activity.entity.PersonDaily;
import com.minivision.machinefacerecognition.activity.entity.PersonFaces;

import com.minivision.machinefacerecognition.activity.dailydb.PersonDailyDao;
import com.minivision.machinefacerecognition.activity.dailydb.PersonFacesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDailyDaoConfig;
    private final DaoConfig personFacesDaoConfig;

    private final PersonDailyDao personDailyDao;
    private final PersonFacesDao personFacesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDailyDaoConfig = daoConfigMap.get(PersonDailyDao.class).clone();
        personDailyDaoConfig.initIdentityScope(type);

        personFacesDaoConfig = daoConfigMap.get(PersonFacesDao.class).clone();
        personFacesDaoConfig.initIdentityScope(type);

        personDailyDao = new PersonDailyDao(personDailyDaoConfig, this);
        personFacesDao = new PersonFacesDao(personFacesDaoConfig, this);

        registerDao(PersonDaily.class, personDailyDao);
        registerDao(PersonFaces.class, personFacesDao);
    }
    
    public void clear() {
        personDailyDaoConfig.clearIdentityScope();
        personFacesDaoConfig.clearIdentityScope();
    }

    public PersonDailyDao getPersonDailyDao() {
        return personDailyDao;
    }

    public PersonFacesDao getPersonFacesDao() {
        return personFacesDao;
    }

}
